
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: import-app-gazin-cors
plugin: cors
config:
  origins:
    - https://devportal-homolog.apr.vee.codes
    - https://devportal.apr.vee.codes
  credentials: false
  max_age: 3600
  preflight_continue: false
---
apiVersion: v1
kind: Service
metadata:
  name: import-app-gazin-service-0
spec:
  externalName: rest.demo.vee.codes
  type: ExternalName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: import-app-gazin
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: import-app-gazin-cors
spec:
  rules:
    - host: kong.vkpr.platform.vee.codes
      http:
        paths:
          - backend:
              service:
                name: import-app-gazin-service-0
                port:
                  number: 80
            path: /import-app-gazin/sample-app/.*
            pathType: ImplementationSpecific
  ingressClassName: kong
